---
- name: Set up new machine
  hosts: localhost
  pre_tasks:
    - name: Check if .asdf file exists
      ansible.builtin.stat:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.asdf"
      register: asdf_file
  tasks:
    - name: Execute OSX settings update
      ansible.builtin.import_tasks: tasks/osx.yml
      when: ansible_facts['os_family'] | lower == "darwin"
      tags:
        - osx
    - name: Enhance ohmyzsh installation
      ansible.builtin.import_tasks: tasks/zsh.yml
      when: ansible_facts['os_family'] | lower == "darwin"
      tags:
        - zsh
    - name: Set up Python
      ansible.builtin.import_tasks: tasks/python.yml
      when: ansible_facts['os_family'] | lower == "darwin"
      tags:
        - python
  roles:
    - role: elliotweiser.osx-command-line-tools
      when: ansible_facts['os_family'] | lower == "darwin"
      tags:
        - osx
    - role: geerlingguy.mac.homebrew
      when: ansible_facts['os_family'] | lower == "darwin"
      tags:
        - osx
    - role: geerlingguy.mac.mas
      when: ansible_facts['os_family'] | lower == "darwin" and (mas_installed_apps or mas_installed_app_ids)
      tags:
        - osx
    - role: geerlingguy.mac.dock
      when: ansible_facts['os_family'] | lower == "darwin" and configure_dock
      tags:
        - osx
    - role: osx_provisioner.asdf
      when: not asdf_file.stat.exists
      asdf_plugins:
        - name: "nodejs"
          versions: ["18.9.0"]
          global: "18.9.0"
        - name: "python"
          versions: ["3.9.1"]
    - role: fubarhouse.rust
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ lookup('ansible.builtin.env', 'USER') }}"
  vars_files:
    - default.config.yml
