- name: Set up new machine
  connection: local
  hosts: localhost
  pre_tasks:
    - name: If osx, install command line tooling
      ansible.builtin.command: zsh ./bin/osx.zsh
      changed_when: false
      become_method: su
      when: ansible_facts['os_family'] == "Darwin"
      tags:
        - osx
  tasks:
    - name: Create temp dir for downloads
      ansible.builtin.file:
        path: $HOME/temp-downloads/
        state: directory
        mode: "0755"
    - name: Execute OSX settings update
      ansible.builtin.import_tasks: tasks/osx.yml
    - name: Set up ohmyzsh
      ansible.builtin.import_tasks: tasks/zsh.yml
    - name: Install ASDF and node
      ansible.builtin.import_tasks: tasks/node.yml
    - name: Install Rust
      ansible.builtin.import_tasks: tasks/rust.yml
      # stow + dotfiles
      # set up vscode settings
      # yabai window manager
      # check out alacritty and embed in vscode terminal
      # https://github.com/alacritty/alacritty/blob/master/INSTALL.md#zsh

      # explore git worktrees instead of normal git
      # learn some core utils
      # cat
      # read
      # grep / rg (rust version of grep)
      # tr
      # echo
      # sed
      # sort
      # bc
      # check out vimtutor
  post_tasks:
    - name: Remove temp downloads directory
      ansible.builtin.file:
        path: $HOME/temp-downloads/
        state: absent
  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags:
        - homebrew
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags:
        - mas
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags:
        - dock
  vars_files:
    - default.config.yml
