---
collections:
  - name: community.general
  - name: geerlingguy.mac
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: fubarhouse.rust
  - name: gantsign.oh-my-zsh
  - name: osx_provisioner.asdf
