- name: Install Python packages
  block:
    - name: Pipx ensure path
      ansible.builtin.command: pipx ensurepath
    - name: Source .zshrc to ensure pipx if it installed
      ansible.builtin.shell: "source {{ lookup('ansible.builtin.env', 'HOME') }}/.zshrc"
