- name: Zsh tasks
  become: "{{ should_be_root }}"
  block:
    - name: Check if .config directory exists
      ansible.builtin.stat:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config"
      register: config_dir
    - name: Create .config directory if it does not exist
      ansible.builtin.file:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/"
        owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
        state: directory
        mode: 0755
      when: config_dir.stat.isDir is defined and not config_dir.stat.isDir
    - name: Clone repo for zsh-suggestions
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions"
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        version: v0.7.0
    - name: Clone repo for zsh-syntax-highlighting
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-syntax-highlighting"
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
        version: v0.7.1
    - name: Copy zsh files to ZSH_CUSTOM
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.oh-my-zsh/custom/"
        owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
        mode: 0755
        force: true
      with_fileglob: templates/.config/*
    - name: "Create a default ZSH configuration"
      ansible.builtin.template:
        src: templates/.zshrc
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.zshrc"
        owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
        mode: 0755
        force: true
    - name: Add Starship configuration to ~/.config
      ansible.builtin.template:
        src: templates/starship.toml
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/starship.toml"
        owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
        mode: 0755
        force: true
      when: config_dir.stat.exists
