- name: Zsh tasks
  become: "{{ should_be_root }}"
  block:
    - name: Install ohmyzsh
      ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh"
      tags:
        - zsh
    - name: Set ZSH as the default shell
      ansible.builtin.shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
      become: true
      register: my_output # <- Registers the command output.
      changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.
    - name: Install the ohmyzsh plugin autosuggestions
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: ~/.oh-my-zsh/plugins/zsh-autosuggestions
        version: a411ef3e0992d4839f0732ebeb9823024afaaaa8
      tags:
        - zsh
    - name: Create root .config
      ansible.builtin.template:
        src: templates/.config/
        dest: /Users/{{ lookup('env', 'USER') }}/.config/
        owner: "{{ lookup('env', 'USER') }}"
        mode: "0755"
        force: true
      tags:
        - zsh
    - name: "Create a default ZSH configuration"
      ansible.builtin.template:
        src: templates/.zshrc
        dest: /Users/{{ lookup('env', 'USER') }}/.zshrc
        owner: "{{ lookup('env', 'USER') }}"
        mode: "0755"
        force: true
      tags:
        - zsh
    - name: Replace zsh plugins entry
      ansible.builtin.lineinfile:
        path: /Users/{{ lookup('env', 'USER') }}/.zshrc
        regexp: "plugins=.*"
        line: plugins=(git zsh-autosuggestions)
        owner: "{{ lookup('env', 'USER') }}"
        mode: "0755"
      tags:
        - zsh
